# Generated by Django 5.0.4 on 2024-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('customer', 'Заказчик'), ('customer', 'Исполнитель')], default='customer', verbose_name='Тип'),
        ),
    ]
